AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: >
  interactive-live-stream-poll-service

Globals:
  Function:
    Timeout: 5
    Environment:
      Variables:
        POLL_TABLE_NAME: InteractiveLiveStreamPoll

Resources:
  CreatePollFunction:
    Type: AWS::Serverless::Function 
    Properties:
      CodeUri: handlers/create-poll/
      Handler: create-poll
      Runtime: go1.x
      Architectures:
        - x86_64
      Events:
        CatchAll:
          Type: Api 
          Properties:
            Path: /polls
            Method: POST
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref InteractiveLiveStreamPoll

  InteractiveLiveStreamPoll:
    Type: AWS::DynamoDB::Table
    Properties:
      AttributeDefinitions:
        - AttributeName: PK
          AttributeType: S
        - AttributeName: SK
          AttributeType: S
      KeySchema:
        - AttributeName: PK
          KeyType: HASH
        - AttributeName: SK
          KeyType: RANGE
      ProvisionedThroughput:
        ReadCapacityUnits: 1
        WriteCapacityUnits: 1
      TableName: "InteractiveLiveStreamPoll"
      
Outputs:
  CreatePollAPI:
    Description: "Create poll endpoint"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/polls/"
