AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: >
  interactive-live-stream-poll-service

Globals:
  Function:
    Timeout: 5
    Environment:
      Variables:
        POLL_TABLE_NAME: InteractiveLiveStreamPoll

Resources:
  CreatePollFunction:
    Type: AWS::Serverless::Function 
    Properties:
      Handler: ./bin/create-poll
      CodeUri: ./
      Runtime: go1.x
      Architectures:
        - x86_64
      Events:
        CatchAll:
          Type: Api 
          Properties:
            Path: /polls
            Method: POST
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref InteractiveLiveStreamPoll

  BroadcastPoll:
    Type: AWS::Serverless::Function
    Properties:
      Handler: ./bin/broadcast-poll
      CodeUri: ./
      Runtime: go1.x
      Architectures:
        - x86_64
      Policies: 
        - DynamoDBCrudPolicy:
            TableName: !Ref InteractiveLiveStreamPoll
        - Version: '2012-10-17'
          Statement:
          - Effect: Allow
            Action:
              - 'ivs:PutMetadata'
            Resource: '*'
      Events:
        Stream:
          Type: DynamoDB
          Properties:
            Stream: !GetAtt InteractiveLiveStreamPoll.StreamArn
            BatchSize: 1
            StartingPosition: LATEST
            FilterCriteria:
              Filters:
                - Pattern: "{ \"eventName\": [\"INSERT\"], \"dynamodb\": { \"NewImage\": { \"itemType\": { \"S\": [\"Poll\"] } } }}"

  GetPollFunction:
    Type: AWS::Serverless::Function 
    Properties:
      Handler: ./bin/get-poll
      CodeUri: ./
      Runtime: go1.x
      Architectures:
        - x86_64
      Events:
        CatchAll:
          Type: Api 
          Properties:
            Path: /polls/{id}
            Method: GET
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref InteractiveLiveStreamPoll

  SubmitVoteFunction:
    Type: AWS::Serverless::Function 
    Properties:
      Handler: ./bin/submit-vote
      CodeUri: ./
      Runtime: go1.x
      Architectures:
        - x86_64
      Events:
        CatchAll:
          Type: Api 
          Properties:
            Path: /polls/{id}/votes
            Method: POST
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref InteractiveLiveStreamPoll

  AggregatePollVotes:
    Type: AWS::Serverless::Function 
    Properties:
      Handler: ./bin/aggregate-poll-votes
      CodeUri: ./
      Runtime: go1.x
      Architectures:
        - x86_64
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref InteractiveLiveStreamPoll
        - Version: '2012-10-17'
          Statement:
          - Effect: Allow
            Action:
              - 'ivs:PutMetadata'
            Resource: '*'
      Events:
        Stream:
          Type: DynamoDB
          Properties:
            Stream: !GetAtt InteractiveLiveStreamPoll.StreamArn
            BatchSize: 5
            MaximumBatchingWindowInSeconds: 10
            StartingPosition: LATEST
            FilterCriteria:
              Filters:
                - Pattern: "{ \"eventName\": [\"INSERT\"], \"dynamodb\": { \"NewImage\": { \"itemType\": { \"S\": [\"Vote\"] } } }}"

  InteractiveLiveStreamPoll:
    Type: AWS::DynamoDB::Table
    Properties:
      AttributeDefinitions:
        - AttributeName: PK
          AttributeType: S
        - AttributeName: SK
          AttributeType: S
      KeySchema:
        - AttributeName: PK
          KeyType: HASH
        - AttributeName: SK
          KeyType: RANGE
      ProvisionedThroughput:
        ReadCapacityUnits: 1
        WriteCapacityUnits: 1
      TableName: "InteractiveLiveStreamPoll"
      StreamSpecification:
        StreamViewType: NEW_IMAGE
      
Outputs:
  CreatePollAPI:
    Description: "Create poll endpoint"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/polls"
  GetPollAPI:
    Description: "Get poll endpoint"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/polls/:id"
  SubmitVoteAPI:
    Description: "Create vote endpoint"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/polls/:id/votes"
